# Generated by Django 5.1.1 on 2024-10-04 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='password',
        ),
    ]
